version: '3.8'
services:
  db:
    container_name: aspace_db
    image: mysql:8.2.0
    command: --character-set-server=UTF8MB4 --innodb_buffer_pool_size=2G --innodb_buffer_pool_instances=2 --log_bin_trust_function_creators=1
    ports:
        - "3306:3306"
    environment:
        - MYSQL_ROOT_PASSWORD=password
        - MYSQL_DATABASE=archivesspace
        - MYSQL_USER=as
        - MYSQL_PASSWORD=as123
    networks:
        - aspace-local
    volumes:
        - ./dbsnapshots:/dbsnapshots/
        - ./db:/var/lib/mysql

networks:
    aspace-local:
        name: aspace-local
